version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: beta
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
    - 5.1.2
  - dependency-name: got
    versions:
    - 11.8.1
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
