language: node_js

env:
  - NODE_ENV=development

install:
  - npm install

script:
  - npm test

after_success:
  - npx codecov

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      branch: develop

notifications:
  email:
    on_success: never
