language: node_js

env:
  - NODE_ENV=development

install:
  - npm install

script:
  - npm test
  - npx codecov

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      master: true
      develop: true

notifications:
  email:
    on_success: never
